''' Script to get latitude and longitude of French cities and save them to a CSV file.'''

import pandas as pd
from src.geocoders_file import Geocoders

cities = [
    "Paris",
    "Lyon",
    "Marseille",
    "Lille",
    "Bordeaux",
    "Toulouse",
    "Nice",
    "Nantes",
    "Strasbourg",
    "Montpellier",
    "Rennes",
    "Reims",
    "Le Havre",
    "Saint-Étienne",
    "Toulon",
    "Grenoble",
    "Dijon",
    "Angers",
    "Nîmes",
    "Villeurbanne",
    "Clermont-Ferrand",
    "Le Mans",
    "Aix-en-Provence",
    "Brest",
    "Tours",
    "Amiens",
    "Limoges",
    "Annecy",
    "Perpignan",
    "Besançon",
    "Metz",
    "Nancy",
    "Avignon",
    "La Rochelle",
    "Pau",
    "Bayonne",
    "Albi",
    "Rodez",
    "Cahors",
    "Montauban",
    "Agen",
    "Auch",
    "Foix",
    "Carcassonne",
    "Narbonne",
    "Béziers",
    "Sète",
    "Mende",
    "Millau",
    "Brive-la-Gaillarde",
    "Tarbes",
    "Saint-Gaudens",
    "Agde",
    "Narbonne-Plage",
    "Poitiers",
    "Niort",
    "La Roche-sur-Yon",
    "Angoulême",
    "Périgueux",
    "Bergerac",
    "Libourne",
    "Arcachon",
    "Dax",
    "Mont-de-Marsan",
    "Saint-Jean-de-Luz",
    "Aurillac",
    "Saint-Flour",
    "Issoire",
    "Montluçon",
    "Moulins",
    "Nevers",
    "Bourges",
    "Châteauroux",
    "Vierzon",
    "Chartres",
    "Orléans",
    "Blois",
    "Montargis",
    "Riom",
    "Le Puy-en-Velay",
    "Troyes",
    "Chaumont",
    "Langres",
    "Vesoul",
    "Belfort",
    "Mulhouse",
    "Colmar",
    "Haguenau",
    "Saverne",
    "Forbach",
    "Thionville",
    "Verdun",
    "Bar-le-Duc",
    "Épinal",
    "Saint-Dié-des-Vosges",
    "Auxerre",
    "Sens",
    "Dole",
    "Lons-le-Saunier",
    "Saint-Claude",
    "Oyonnax",
    "Bourg-en-Bresse",
    "Autun",
    "Beaune",
    "Villefranche-sur-Saône",
    "Roanne",
    "Montbrison",
    "Annonay",
    "Valence",
    "Montélimar",
    "Romans-sur-Isère",
    "Bollène",
    "Gap",
    "Briançon",
    "Digne-les-Bains",
    "Sisteron",
    "Manosque",
    "Draguignan",
    "Fréjus",
    "Grasse",
    "Cannes",
    "Antibes",
    "Menton",
    "Hyères",
    "Orange",
    "Carpentras",
    "Uzès",
    "Arras",
    "Lens",
    "Douai",
    "Valenciennes",
    "Calais",
    "Boulogne-sur-Mer",
    "Saint-Malo",
    "Lorient",
    "Vannes",
    "Quimper",
    "Morlaix",
    "Saint-Brieuc",
    "Rouen",
    "Évreux",
    "Caen",
    "Cherbourg-en-Cotentin",
    "Versailles",
    "Nanterre",
    "Créteil",
    "Évry-Courcouronnes",
    "Melun",
    "Meaux",
    "Cergy",
    "Laval",
    "Mayenne",
    "Alençon",
    "Flers"
]

rows = []
geocoder = Geocoders()
for city in cities:
    coords = geocoder._geocode_longitude_latitude_method(city)
    lat = coords['latitude']
    lon = coords['longitude']
    rows.append([city, lat, lon])

    print(f"City: {city}, Latitude: {lat}, Longitude: {lon}")

df = pd.DataFrame(rows, columns=["city", "lat", "lon"])
df.to_csv("cities.csv", index=False)